⚙️ Detecting & Fixing Missing / Corrupted Data

In [31]:
import pandas as pd
import numpy as np

data = {
    'Date': ['2025-10-01', '2025-10-02', '2025-10-03', '2025-10-04'],
    'Company': ['TATAMOTORS', 'INFOSYS', 'RELIANCE', 'HDFC'],
    'Price': [894.5, np.nan, 1563.0, 1723.2],
    'Volume': [1234567, 1278900, '-', 1043300],
    'Sector': ['Auto', 'Auto', 'Energy', 'Finance'],
    'Rating': ['A', 'B', np.nan, 'A']
}

df = pd.DataFrame(data)

In [32]:
df.head(2)

         Date     Company  Price   Volume Sector Rating
0  2025-10-01  TATAMOTORS  894.5  1234567   Auto      A
1  2025-10-02     INFOSYS    NaN  1278900   Auto      B

In [33]:
df.tail(2)

         Date   Company   Price   Volume   Sector Rating
2  2025-10-03  RELIANCE  1563.0        -   Energy    NaN
3  2025-10-04      HDFC  1723.2  1043300  Finance      A

1️⃣ Checking for missing or invalid data

In [ ]:
print(df.info())

In [ ]:
print(df.isna())

2️⃣ Fixing the Volume column

We’ll convert it to numeric and tell Pandas to coerce errors into NaN:

In [34]:
df['Volume'] = pd.to_numeric(df['Volume'], errors='coerce')
df.head()

         Date     Company   Price     Volume   Sector Rating
0  2025-10-01  TATAMOTORS   894.5  1234567.0     Auto      A
1  2025-10-02     INFOSYS     NaN  1278900.0     Auto      B
2  2025-10-03    RELIANCE  1563.0        NaN   Energy    NaN
3  2025-10-04        HDFC  1723.2  1043300.0  Finance      A

3️⃣ Handling Missing Data

We can fill or drop them:

In [35]:
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')
df['Price']=df['Price'].fillna(df['Price'].mean())
df['Rating']=df['Rating'].fillna('B')
print(df)

         Date     Company        Price     Volume   Sector Rating
0  2025-10-01  TATAMOTORS   894.500000  1234567.0     Auto      A
1  2025-10-02     INFOSYS  1393.566667  1278900.0     Auto      B
2  2025-10-03    RELIANCE  1563.000000        NaN   Energy      B
3  2025-10-04        HDFC  1723.200000  1043300.0  Finance      A

🧩 Why AI engineers care:
ML models can’t handle missing or string-type data in numeric columns — this cleaning step ensures data integrity.

🧮 Feature Engineering — Making Data Smarter

Feature engineering = creating new useful features from existing ones.

Example:

In [36]:
# convert 'Date' column to datetime format
df['Date'] = pd.to_datetime(df['Date'])

#create new features
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

#add derived matrix price * volume

df['trade_value'] = df['Price'] * df['Volume']
print(df)

        Date     Company        Price     Volume   Sector Rating  Year  Month  \
0 2025-10-01  TATAMOTORS   894.500000  1234567.0     Auto      A  2025     10
1 2025-10-02     INFOSYS  1393.566667  1278900.0     Auto      B  2025     10
2 2025-10-03    RELIANCE  1563.000000        NaN   Energy      B  2025     10
3 2025-10-04        HDFC  1723.200000  1043300.0  Finance      A  2025     10

   Day   trade_value
0    1  1.104320e+09
1    2  1.782232e+09
2    3           NaN
3    4  1.797815e+09